owner: danielpotthast # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: d-photos.de
    url: https://www.d-photos.de
  - name: fs05.de
    url: https://www.fs05.de
  - name: fs05.wiki
    url: https://www.fs05.wiki
  - name: stefanpotthast.de
    url: https://www.stefanpotthast.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.d-photos.de
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
